name: Particles
version: 1.0-SNAPSHOT
description: This plugin is so you can make particles in certain places
author: pokuit
main: effect.pokuit.georgep.HaseEffects
commands:
   particles:
      description: Make particles
      aliases: [parti, effectp]
      permission: particles.admin
      usage: /particles set/remove <EffectType (If set)> [<x>] [<y>] [<z>] [[<world>]]